<?php
/**
 * Vedovato_VedovatoGrid extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Vedovato
 * @package        Vedovato_VedovatoGrid
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Vedovatogrid link widget template
 *
 * @category    Vedovato
 * @package     Vedovato_VedovatoGrid
 * @author      Ultimate Module Creator
 */
?>
<?php $_vedovatogrid = $this->getCurrentVedovatogrid();?>
<?php if ($_vedovatogrid) :?>
    <div class="vedovatogrid-widget-link">
        <a href="<?php echo $_vedovatogrid->getVedovatogridUrl()?>"><?php echo $_vedovatogrid->getNome()?></a>
    </div>
<?php endif;?>
