<?php
/**
 * Vedovato_VedovatoGrid extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Vedovato
 * @package        Vedovato_VedovatoGrid
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Vedovatogrid view template
 *
 * @category    Vedovato
 * @package     Vedovato_VedovatoGrid
 * @author      Ultimate Module Creator
 */
?>
<?php $_vedovatogrid = $this->getCurrentVedovatogrid();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title vedovatogrid-title">
    <h1><?php echo $_vedovatogrid->getNome(); ?></h1>
</div>
<div class="vedovatogrid-view">
    <div class="vedovatogrid-nome">
        <?php echo Mage::helper('vedovato_vedovatogrid')->__('Nome');?>:<?php echo $_vedovatogrid->getNome();?>

    </div>
    <div class="vedovatogrid-telefone">
        <?php echo Mage::helper('vedovato_vedovatogrid')->__('Telefone');?>:<?php echo $_vedovatogrid->getTelefone();?>

    </div>
    <div class="vedovatogrid-descricao">
        <?php echo Mage::helper('vedovato_vedovatogrid')->__('Descrição');?>:<?php echo $_vedovatogrid->getDescricao();?>

    </div>

</div>
